name: Build and Push Docker Image 

# Pemicu Workflow ini berjalan
# Contoh disini ketika ada push ke branch main maka akan memicu workflow
on: 
  workflow_dispatch:

jobs: 
  docker: 
    # Menggunakan server ubuntu terbaru yang disediakan Github
    runs-on: ubuntu-latest

    # Langkah-Langkah melakukan Build 
    steps:

      # Langkah 1 : Checkout atau Mengunduh kode dari Repository 
      # Kode uses didalam steps berisi Perintah menjalankan sebuah Action 
      # Jadi uses didalam action tersebut ada Script yang menjalankan tugas sesuai namanya
      # Seperti Checkout dibawah ini berguna untuk mengunduh kode yang ada di repo
      - name: Checkout repository 
        uses: actions/checkout@v4

      # Langkah 2 : Login ke Docker Hub 
      # Menggunakan Secret pada menu Pengaturan Github 
      - name: Log in to Docker Hub
        uses: docker/login-action@v3 
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Langkah 3 : Menyiapkan Docker Buildx (Builder Modern)
      - name: Set up Docker Buildx 
        uses: docker/setup-buildx-action@v3 
      
      # Langkah 4 : Build dan Push Docker image ke Repository Docker Hub
      - name: Build and Push Docker Image 
        uses: docker/build-push-action@v5
        with: 
          context: . 
          push: true 
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/github-action-nodejs:5.0

